### ISSUE TITLE
Unable to `make` app.

### ISSUE THREAD

**Issue by ocyedwin** [barbalex/kapla4#1]
NOTE: adding this asar config seems to work:
```
  packagerConfig: {
    asar: true,
    ignore: file => {
      return false
    },
  },
```

Encountered the following error when running `make`.
```
$ electron-forge make
√ Checking your system
- Resolving Forge ConfigYou have set packagerConfig.ignore, the Electron Forge webpack plugin normally sets this automatically.

Your packaged app may be larger than expected if you dont ignore everything other than the '.webpack' folder
√ Resolving Forge Config
We need to package your application before we can make it
- Preparing to Package Application for arch: x64You have set packagerConfig.ignore, the Electron Forge webpack plugin normally sets this automatically.

Your packaged app may be larger than expected if you dont ignore everything other than the '.webpack' folder
√ Compiling Main Process Code
√ Compiling Renderer Template
√ Preparing to Package Application for arch: x64
√ Preparing native dependencies
√ Packaging Application
Making for the following targets: squirrel
× Making for target: squirrel - On platform: win32 - For arch: x64

An unhandled error has occurred inside Forge:
An error occured while making for target: squirrel
Failed with exit code: 1
Output:
Attempting to build package from 'Kapla.nuspec'.
Invalid URI: The format of the URI could not be determined.

Error: Failed with exit code: 1
Output:
Attempting to build package from 'Kapla.nuspec'.
Invalid URI: The format of the URI could not be determined.

    at ChildProcess.<anonymous> (C:\Users\...\kapla4\node_modules\electron-winstaller\src\spawn-promise.ts:52:16)
    at ChildProcess.emit (events.js:321:20)
    at ChildProcess.EventEmitter.emit (domain.js:485:12)
    at maybeClose (internal/child_process.js:1026:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
error Command failed with exit code 1.
```

**Comment by barbalex** [comment]
Sorry to say I am no expert at building using electron-forge.

This works for me right now on MacOS:
```
Alexanders-MBP:kapla4 alexandergabriel$ yarn make
yarn run v1.21.1
$ electron-forge make
✔ Checking your system
⠋ Resolving Forge ConfigYou have set packagerConfig.ignore, the Electron Forge webpack plugin normally sets this automatically.

Your packaged app may be larger than expected if you dont ignore everything other than the '.webpack' folder
✔ Resolving Forge Config
We need to package your application before we can make it
⠋ Preparing to Package Application for arch: x64You have set packagerConfig.ignore, the Electron Forge webpack plugin normally sets this automatically.

Your packaged app may be larger than expected if you dont ignore everything other than the '.webpack' folder
✔ Compiling Main Process Code
✔ Compiling Renderer Template
✔ Preparing to Package Application for arch: x64
✔ Preparing native dependencies
⠋ Packaging ApplicationWARNING: Could not find icon "src/etc/app.icns", not updating app icon
✔ Packaging Application
Making for the following targets: zip
✔ Making for target: zip - On platform: darwin - For arch: x64
✨  Done in 42.90s.
```
And it worked two weeks ago on my Windows 10 PC.

My biggest issue was getting a webpack project using native modules to build. More on that here: https://github.com/electron-userland/electron-forge/issues/1224. Which explains the warnings in the output and the size of the built project.
